### ISSUE TITLE
Support Rust async.await ?

### ISSUE THREAD

**Issue by baoyachi** [XAMPPRocky/remove_dir_all#68]
The current view is synchronous, does it support Rust async, await?

Ref:https://docs.rs/tokio/latest/tokio/fs/struct.File.html

**Comment by rbtcollins** [comment]
The parallel implementation internally creates its own threads with rayon. The entry function will block, so you should run it with `spawn_blocking`. I'm interested in either having, or making, a natively async version - I think it will make some of the internals much easier to express, and could lead to smarter handling of extreme conditions (super deep or super branchy trees).

But as @XAMPPRocky says, depending on tokio itself would be problematic - this crate is intended to be usable from both non-async, and other-engine async code, so some modular way to deal with that is important.

**Comment by baoyachi** [comment]
For example, [reqwest](https://github.com/seanmonstar/reqwest) http client support [async_impl](https://github.com/seanmonstar/reqwest/tree/master/src/async_impl) and [blocking](https://github.com/seanmonstar/reqwest/tree/master/src/blocking) optional

**Comment by rbtcollins** [comment]
@baoyachi `reqwest` only supports one async runtime. The way the `blocking` feature works, it creates a Tokio runtime implicitly when you call into it, rather than expecting to find a runtime contextually. This is ok for `reqwest` which started out as an HTTP client for Tokio, but `remove_dir_all` needs to be more circumspect with users dependency chains.
